-- Исходник 1: employees_source_1 (например, выгрузка из Excel)
CREATE TABLE employees_source_1 (
    full_name      VARCHAR2(100),
    birth_date     DATE,
    department     VARCHAR2(50),
    salary         NUMBER(10,2)
);

-- Исходник 2: employees_source_2 (например, данные из API)
CREATE TABLE employees_source_2 (
    first_name     VARCHAR2(50),
    last_name      VARCHAR2(50),
    dob            VARCHAR2(10),  -- строка в формате 'YYYY-MM-DD'
    dept_code      VARCHAR2(10),
    monthly_salary NUMBER
);

-- Целевая таблица: employees_target
CREATE TABLE employees_target (
    employee_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR2(50),
    last_name      VARCHAR2(50),
    birth_date     DATE,
    department     VARCHAR2(50),
    salary         NUMBER(10,2),
    source_system  VARCHAR2(20)
);



-- Данные в employees_source_1
INSERT INTO employees_source_1 (full_name, birth_date, department, salary) VALUES ('John Smith', TO_DATE('1985-04-12', 'YYYY-MM-DD'), 'HR', 4500);
INSERT INTO employees_source_1 (full_name, birth_date, department, salary) VALUES ('Alice Johnson', TO_DATE('1990-09-30', 'YYYY-MM-DD'), 'IT', 5500);
INSERT INTO employees_source_1 (full_name, birth_date, department, salary) VALUES ('Bob White', TO_DATE('1982-12-01', 'YYYY-MM-DD'), 'Sales', 5000);
-- (добавьте при желании ещё)

-- Данные в employees_source_2
INSERT INTO employees_source_2 (first_name, last_name, dob, dept_code, monthly_salary) VALUES ('Michael', 'Brown', '1987-02-18', 'HR', 4600);
INSERT INTO employees_source_2 (first_name, last_name, dob, dept_code, monthly_salary) VALUES ('Diana', 'Miller', '1992-06-21', 'IT', 5800);
INSERT INTO employees_source_2 (first_name, last_name, dob, dept_code, monthly_salary) VALUES ('George', 'Taylor', '1980-10-09', 'Sales', 5200);
-- (ещё при необходимости)



-- Загрузка из source_1
INSERT INTO employees_target (first_name, last_name, birth_date, department, salary, source_system)
SELECT
    SUBSTR(full_name, 1, INSTR(full_name, ' ') - 1) AS first_name,
    SUBSTR(full_name, INSTR(full_name, ' ') + 1) AS last_name,
    birth_date,
    department,
    salary,
    'SRC1'
FROM employees_source_1;

-- Загрузка из source_2
INSERT INTO employees_target (first_name, last_name, birth_date, department, salary, source_system)
SELECT
    first_name,
    last_name,
    TO_DATE(dob, 'YYYY-MM-DD') AS birth_date,
    dept_code,
    monthly_salary,
    'SRC2'
FROM employees_source_2;


select * 
from employees_source_1;

select * 
from employees_source_2;

select * 
from employees_target;
